version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=1234
      - NODE_ENV=production
    restart: always
